### PR TITLE
Added PortInfo.active

### PR DESCRIPTION
**Pull request by alex3d**

### CODE REVIEW

**Comment by mk-fg** [comment]
Um, shouldn't it be "available", not "active"?

That is, as per `src/pulse/introspect.h`:

```
/** Stores information about a specific port of a sink.  Please
 * note that this structure can be extended as part of evolutionary
 * API updates at any time in any new release. \since 0.9.16 */
typedef struct pa_sink_port_info {
    const char *name;                   /**< Name of this port */
    const char *description;            /**< Description of this port */
    uint32_t priority;                  /**< The higher this value is, the more useful this port is as a default. */
    int available;                      /**< A flags (see #pa_port_available), indicating availability status of this port. \since 2.0 */
} pa_sink_port_info;
...
/** Stores information about a specific port of a source.  Please
 * note that this structure can be extended as part of evolutionary
 * API updates at any time in any new release. \since 0.9.16 */
typedef struct pa_source_port_info {
    const char *name;                   /**< Name of this port */
    const char *description;            /**< Description of this port */
    uint32_t priority;                  /**< The higher this value is, the more useful this port is as a default. */
    int available;                      /**< A flags (see #pa_port_available), indicating availability status of this port. \since 2.0 */
} pa_source_port_info;
```

Both seem to be identical and have "available" there, which sounds like a different thing from "active", as in "one that corresponds to active_port pointer".

**Comment by mk-fg** [comment]
I suspect that one of the following is true:

- By "active" you meant "available", entirely different thing from "active_port" on pa_sink_info/pa_source_info structs.

- That "available" int actually means "this port is active_port", comments are a bit wrong and name of that struct element is somewhat confusing.

Is it one of these cases or maybe something else entirely?

**Comment by mk-fg** [comment]
I've changed that to "available" and guess I'll add enum/translation of that value according to pa_port_available in `src/pulse/def.h`:
```
/** Port availability / jack detection status
 * \since 2.0 */
typedef enum pa_port_available {
    PA_PORT_AVAILABLE_UNKNOWN = 0, /**< This port does not support jack detection \since 2.0 */
    PA_PORT_AVAILABLE_NO = 1,      /**< This port is not available, likely because the jack is not plugged in. \since 2.0 */
    PA_PORT_AVAILABLE_YES = 2,     /**< This port is available, likely because the jack is plugged in. \since 2.0 */
} pa_port_available_t;
```

Thanks!

**Comment by mk-fg** [comment]
Further renamed it to "available_state" so it'd be less likely interpreted to be True/False bool, as simple "available" name might imply.

Values for "available_state" are from PulsePortAvailableEnum (yes/no/unknown), but simple strings can also be used, new README section on enums has more details: https://github.com/mk-fg/python-pulse-control/#enumerated-named-values-enums

**Comment by alex3d** [comment]
Whoops, I've misread pulseaudio sources. Of course it should be `available`. Thanks.

**Pull request merged**
